refactor
akai-org/planer-podrozy pull request #47
Opened 2023-03-22 14:49 UTC by Laskos-p

- fastapi users
- async session
- pre-commit fix

2023-03-26 18:57 UTC, Fuligor requested changes

2023-03-26 18:57 UTC, Fuligor commented on api/src/auth/models.py
> +#     )
raczej starał bym się usuwać "skomentowany kod", bo zaciemnia trochę to co się dzieje w pliku, a jak ktoś chce odzyskać to co było wcześniej to można to łatwo zrobić z gitem ;)

2023-03-26 18:57 UTC, Fuligor commented on api/src/auth/models.py
> +    pass
nie wiem czy jest sens definiować "pustą" klasę, która po prostu dziedziczy z DeclarativeBase

2023-03-26 18:57 UTC, Fuligor commented on api/src/auth/router.py
> +#     return new_user
W sumie to samo co wyżej

2023-03-26 18:57 UTC, Fuligor commented on api/src/database/__init__.py
>  # metadata = sqlalchemy.MetaData()
również ten komentarz można usunąć

2023-03-26 18:57 UTC, Fuligor commented on api/src/database/__init__.py
> +# Base = declarative_base()
kolejne komentarze

2023-03-26 18:57 UTC, Fuligor commented on api/src/database/__init__.py
> +#         db.close()
jak wyżej

2023-03-26 18:57 UTC, Fuligor commented on api/src/auth/router.py
> +# from database import get_db
też komentarze

2023-03-26 18:57 UTC, Fuligor commented on api/src/models.py
> +    )
w zasadzie powiela to kod napisany w "auth/models" w takim razie raczej usunął bym plik "auth/models", bo inaczej mogą nam powstać problemy z uczymaniem bazy danych i dwóch plików kodu

2023-03-28 18:29 UTC, Fuligor commented on api/src/auth/models.py
> +    pass
Tak, ale w zasadzie nie daje nam to nic nowego, bo kolejne klasy wtedy dziedziczą, po klasie Base, a tak dziedziczyły by po DeclarativeBase, i wszystkie dodatkowe właściwości zostaną zainicjowane. Wydaje mi się, że lepszym rozwiązaniem będzie stworzenie aliasu do DeclarativeBase, po przez 
`Base = DeclarativeBase`
zamiast tworzenia osobnej klasy, ale to w zasadzie tylko moja opinia.

2023-03-28 18:31 UTC, Fuligor approved these changes

2023-03-28 20:46 UTC, kyrstke approved these changes

2023-03-29 06:25 UTC, merged