fastapi users
akai-org/planer-podrozy pull request #63
Opened 2023-03-29 06:26 UTC by Laskos-p

2023-04-05 10:48 UTC, Fuligor requested changes

2023-04-05 10:48 UTC, Fuligor commented on api/requirements/docker.txt
> +makefun==1.15.1
na pewno potrzebujemy tej biblioteki? ogólnie czy potrzebujemy tych wszystkich bibliotek? na mainie, jest w miarę aktualny  plik requirements, może najlepiej było by się po prostu do niego wrócić?

2023-04-05 10:48 UTC, Fuligor commented on api/src/config.py
> +    f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgres/{POSTGRES_DB}"
nie jestem przekonany czy już na tym etapie projektu potrzebujemy async, ale jak jest to niech już zostanie

2023-04-11 11:32 UTC, kyrstke commented on api/src/auth/models.py
Nie mam pewności, ale możliwe, że przy mergowaniu trzeba będzie uważać na to jakie zmiany zostaną zaakceptowane (trzeba zachować zawartość tego pliku, bo powstał on po otwarciu tego PR i zmiana wyświetla się jako usunięcie jego zawartości)

2023-04-11 11:35 UTC, kyrstke commented on api/src/auth/router.py
> Nie mam pewności, ale możliwe, że przy mergowaniu trzeba będzie uważać na to jakie zmiany zostaną zaakceptowane (trzeba zachować zawartość tego pliku, bo powstał on po otwarciu tego PR i zmiana wyświetla się jako usunięcie jego zawartości)

Tutaj tak samo

2023-05-08 13:57 UTC, closed without merging