Database model
akai-org/planer-podrozy pull request #65
Opened 2023-03-29 18:33 UTC by siemieniuk

Utworzony projekt bazy na podstawie schematu. Ograniczyłem również niektóre pola w zakresie nulli. Nie ma w chwili tworzenia PR mechanizmu przechowywania współrzędnych.

2023-03-30 16:59 UTC, Fuligor reviewed
Ogólnie mega fajna robota :)

2023-03-30 16:59 UTC, Fuligor commented on api/src/models.py
> +    # TODO: coordinates
w sumie jak tak myślę, to nie wydaje mi się złym pomysłem zapisywanie współrzędnych w bazie danych jako int ze znakiem (zapisywane będzie wtedy współrzędna w postaci minut od początku układu- punktu zero zero, według wzoru _wartość = stopnie * 60 + minuty_), i wtedy odczytywanie ich sprowadzało by się do konfesji odwrotnej, czyli _stopie = wartość // 60_ _minuty = wartość - 60 * stopnie_. Oczywiście najlepiej było by to obudować w _Custom Type_ jak opisano tutaj: https://docs.sqlalchemy.org/en/20/core/custom_types.html

Oczywiście pomysł można w miarę łatwo rozszerzyć do sekund, wtedy dostajemy już dokładność lokalizacji do pojedynczych metrów.

@marcol13, @siemieniuk co myślicie o takim pomyśle?

2023-03-31 18:20 UTC, Maksymilian-Plywaczyk approved these changes

2023-03-31 23:12 UTC, marcol13 commented on api/src/models.py
> +    # TODO: coordinates
Ja nie wiem, czy mimo wszystko nie zapisywałbym tego jako `string` (no ewentualnie `float`) w formie:
```python
#Poznań coordinates
lat = 52.409538
lon = 16.931992
```

Funkcje, które korzystają ze współrzędnych, raczej nie biorą jako argument liczby całkowitoliczbowej. Więc ja bym nie robił sobie dodatkowej roboty, implementując ten konwerter 😜

2023-04-02 11:07 UTC, siemieniuk commented on api/src/models.py
> +    # TODO: coordinates
Znalazłem ku temu dedykowaną bibliotekę: GeoAlchemy2: https://geoalchemy-2.readthedocs.io/en/latest/
Jednak nasz Docker nie jest w stanie jej obsłużyć. Nie ma odpowiedniego pakietu dla alpine. Jeżeli byśmy mieli użyć GeoAlchemy2, niezbędna byłaby zmiana image dockera na np. Debian.

2023-04-02 16:47 UTC, Fuligor commented on api/src/models.py
> +    # TODO: coordinates
Jak masz gotowe rozwiązanie to super, pogadamy po spotkaniu co tam nie działa :)

2023-04-02 23:56 UTC, siemieniuk commented on api/src/models.py
> +    # TODO: coordinates
Już wszystko działa :)
Wypchnąłem w nowych commitach

2023-04-05 10:42 UTC, Fuligor requested changes

2023-04-05 10:42 UTC, Fuligor commented on api/requirements/docker.txt
> +GeoAlchemy2
w requirementes zawsze specyfikuj konkretną wersję biblioteki (przynajmniej do większych wersji np. 2.0.*), bo potem jak wprowadzą zmianę w bibliotece to może cała aplikacja przez to wysiąść

2023-04-12 17:02 UTC, closed without merging