Feature/change password
akai-org/planer-podrozy pull request #90
Opened 2023-05-18 16:53 UTC by Maksymilian-Plywaczyk

Wystawiłem PR, który dodał endpoint /me z dwoma metodami GET, PATCH. Aktualizujące dane usera. Posłużyłem się wbudowaną funkcją z biblioteki fastapi_users. Poprawiony został również prefix w naszym endpoincie /token, z auth -> api, który jest zgodny z naszymi prefixami.

2023-05-21 07:42 UTC, kyrstke commented on api/src/auth/utils.py
> -        require the user to be verified or not. Defaults to False.
to tylko komentarz, ale chyba powinno zostać

2023-05-21 07:43 UTC, kyrstke submitted a review, later dismissed

2023-05-21 08:52 UTC, kyrstke reviewed
Przejrzałem sobie te zmiany jeszcze raz i zauważyłem, że endpoint do zmiany hasła jest już domyślnie utworzony przez router naszego authentication backend (api/reset-password), natomiast endpoint api/me (PATCH) pozwala zmienić dowolne pole, w tym hasło, ale też email, co chyba nie powinno być możliwe. Niestety nie udało mi się tego przetestować, bo nie działa mi ten endpoint (zarówno GET jak i PATCH) - najpewniej przez to, że nie wiem gdzie dołączyć token. W przypadku api/reset-password token wysyła się w body, choć próba zresetowania hasła kończy się Internal Server Errorem.

2023-05-21 09:21 UTC, kyrstke commented on api/src/auth/schemas.py
> +class UserRead(schemas.BaseUser[uuid.UUID]):
Jeśli nikt tego nie zmieniał to u nas kluczem głównym jest Integer. Myślałem nad zmianą na UUID, ale ostatecznie zostaliśmy przy Integer

2023-05-22 07:25 UTC, Maksymilian-Plywaczyk commented on api/src/auth/schemas.py
> +class UserRead(schemas.BaseUser[uuid.UUID]):
Tak jasne dzisiaj to będę zmieniał.

2023-05-22 20:07 UTC, Fuligor requested changes

2023-05-22 20:48 UTC, merged