58 endpoint aktywacji konta
akai-org/planer-podrozy pull request #91
Opened 2023-05-21 11:17 UTC by kyrstke

2023-05-21 11:36 UTC, kyrstke commented
@Fuligor sprawdzisz czemu isort nie przechodzi? Puściłem u siebie `isort .` a potem `black .`.

2023-05-21 12:13 UTC, Fuligor commented
> @Fuligor sprawdzisz czemu isort nie przechodzi? Puściłem u siebie `isort .` a potem `black .`.

a odpalałeś isorta i blacka z głównego katalogu projektu?

2023-05-21 12:49 UTC, kyrstke commented
> > @Fuligor sprawdzisz czemu isort nie przechodzi? Puściłem u siebie `isort .` a potem `black .`.
> 
> a odpalałeś isorta i blacka z głównego katalogu projektu?

tak

2023-05-21 20:39 UTC, Fuligor commented
> > > @Fuligor sprawdzisz czemu isort nie przechodzi? Puściłem u siebie `isort .` a potem `black .`.
> > 
> > 
> > a odpalałeś isorta i blacka z głównego katalogu projektu?
> 
> tak, nawet zalogował, że poprawił te 2 pliki, które powodują błąd

dobra trochę nie wiem o co chodzi 😢 odpaliłem lintery u siebie i przechodzi

2023-05-22 19:33 UTC, Maksymilian-Plywaczyk commented on api/src/auth/manager.py
> +class EmailSchema(BaseModel):
Moim zdaniem warto EmailSchema przerzucić do pliku ze Schemasami. Daje to lepszą przejrzystość oraz mamy pewność, że to tam w przyszłości znajdziemy.

2023-05-22 19:35 UTC, Maksymilian-Plywaczyk requested changes
Ja bym zalecił zmianę przy tym co zostawiłem komentarz i będzie można mergować ;)

2023-05-22 19:54 UTC, kyrstke commented on api/src/auth/manager.py
> +class EmailSchema(BaseModel):
Wydaje mi się, że to spoko pomysł, ale niech @Fuligor potwierdzi

2023-05-22 20:21 UTC, Fuligor requested changes

2023-05-22 20:21 UTC, Fuligor commented on api/src/auth/manager.py
> +class EmailSchema(BaseModel):
ta zdecydowanie wrzuciłbym do schemas

2023-05-22 20:21 UTC, Fuligor commented on api/src/auth/manager.py
> +        # TODO send welcome email
Może trzeba zrobić taska na to żeby potem nie zapomnieć że to tutaj wisi

2023-05-22 20:21 UTC, Fuligor commented on api/src/auth/router/__init__.py
> +# TODO: change requires verification to True when verification added
Warto usunąć te TODO skoro jest już zrobione

2023-05-22 20:50 UTC, Maksymilian-Plywaczyk commented on api/src/auth/manager.py
> +        # TODO send welcome email
Też myślę, że warto to wrzucić jako task i to wykonać.

2023-05-23 13:49 UTC, kyrstke commented on api/src/auth/manager.py
> +        # TODO send welcome email
Done

2023-05-23 13:49 UTC, kyrstke commented on api/src/auth/router/__init__.py
> +# TODO: change requires verification to True when verification added
Done

2023-05-25 16:40 UTC, Maksymilian-Plywaczyk commented on api/src/auth/manager.py
> +class EmailSchema(BaseModel):
Ja bym jak już wydzielił w pliku konfiguracyjnym lub też zostawił tak jak jest. W schemas bym tego nie wrzucał.

2023-05-25 19:57 UTC, kyrstke commented on api/src/auth/manager.py
> +class EmailSchema(BaseModel):
Ok, to zrobię osobny plik konfiguracyjny, może znajdę w projekcie coś jeszcze co powinno tam być, a jak nie to chociaż będzie miejsce na wszystkie takie rzeczy.

2023-05-28 10:44 UTC, Fuligor approved these changes

2023-05-28 14:38 UTC, Maksymilian-Plywaczyk approved these changes

2023-05-28 14:39 UTC, merged